<a href="https://colab.research.google.com/github/hussain2505/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Version

In [29]:
import numpy as np

print(np.__version__)

2.0.2


1D array

In [30]:

a = np.array([10, 20, 30, 40, 50])

print(a)

[10 20 30 40 50]


2D array

In [31]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(data)

[[10 20 30]
 [40 50 60]]


NumPy properties

In [32]:
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)

(2, 3)
2
6
int64


Indexing

In [33]:
print(a[0])
print(a[2])
print(a[-1])

10
30
50


Slicing

In [34]:
print(a[1:4])

[20 30 40]


In [35]:
print(a[:2])
print(data[1:])

[10 20]
[[40 50 60]]


Mathematical operations

In [36]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


Statistical functions

In [37]:
data = np.array([10, 20, 30, 40, 50])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))
print(np.min(data))
print(np.max(data))
print(np.sum(data))

30.0
30.0
14.142135623730951
200.0
10
50
150


Working with missing values


In [38]:
data = np.array([10, 20, np.nan, 40, 50])

print(np.mean(data))

nan


In [39]:
print(np.nanmean(data))
print(np.nansum(data))
print(np.nanmin(data))
print(np.nanmax(data))
print(np.isnan(data))

30.0
120.0
10.0
50.0
[False False  True False False]


 np.concatenate

In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)

[1 2 3 4 5 6]


Reshape

In [41]:
a = np.arange(1, 7)

print(a.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


Boolean filtering

In [42]:
data = np.array([10, 25, 30, 45, 50])

print(data[data > 30])

[45 50]


Create special array

Zeros

In [43]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Ones

In [44]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Arrange

In [45]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])